VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/debian-8.6"

  config.vm.hostname = "toy"

  config.vm.synced_folder ".", "/toy"

  config.ssh.forward_agent = true

  config.vm.provider "parallels" do |v|
    v.memory = 1024
    v.cpus = 2
  end
end
